Repository redhat-beyond/Hotails, pull requests merged in 2022-05, with the labels that each got.

#64 Adding Homepage for daycare user
  conftest.py
  daycare/templates/daycare/daycare-homepage.html
  daycare/test_daycare.py
  daycare/views.py
  main/templates/main/base_template.html
  main/tests.py
  main/views.py
Labels: Ready for review

#98 Create Shared conftest file
  conftest.py
  dogowner/test_dog_owner.py
  main/tests.py
  message/tests.py
  orders/tests.py
  review/conftest.py
  review/tests.py
Labels: Status/New, Ready for review

#67 Adding homepage for dog owner
  daycare/models.py
  daycare/test_image.py
  dogowner/templates/dogowner/dog_owner_homepage.html
  dogowner/views.py
  main/tests.py
  main/urls.py
  main/views.py
  static/CSS/dog_owner_homepage.css
  static/images/daycare-default-profile-image.jpeg
Labels: Ready for review

#97 Create static orders
  orders/migrations/0003_static_orders.py
  orders/models.py
Labels: Ready for review, simple

#100 Adding message and chat HTML
  Hotails/urls.py
  main/templates/main/base_template.html
  main/views.py
  message/templates/chat.html
  message/templates/messages.html
  message/test_html.py
  message/views.py
  static/CSS/chat.css
Labels: Status/New, Ready for review
