Repository redhat-beyond/Hotails, pull requests merged in 2022-04, with the labels that each got.

#52 Change the name of the ERD image
  resources/documents/HotailsDatabaseERD.png
  resources/documents/README.md
Labels: bug, documentation

#46 Creating orders app
  Hotails/settings.py
  orders/__init__.py
  orders/admin.py
  orders/apps.py
  orders/migrations/0001_initial.py
  orders/migrations/0002_test_data.py
  orders/migrations/__init__.py
  orders/models.py
  orders/tests.py
  orders/views.py
Labels: Ready for merge

#37 Adding message model
  Hotails/settings.py
  message/__init__.py
  message/admin.py
  message/apps.py
  message/migrations/0001_initial.py
  message/migrations/0002_test_data.py
  message/migrations/__init__.py
  message/models.py
  message/tests.py
  message/views.py
Labels: Ready for merge

#56 Creating a navigation bar for Hotails templates
  main/templates/main/base_template.html
  main/templates/main/homepage screenshots/Homepage - Daycare Owner.png
  main/templates/main/homepage screenshots/Homepage - Dog Owner.png
  main/templates/main/homepage screenshots/Homepage - Welcome.png
  main/templates/main/homepage.html
  static/images/Hotails-logo-smaller.png
Labels: Ready for review

#60 🖼️ Adding the possibility for a daycare owner to upload images to his daycare
  daycare/conftest.py
  daycare/migrations/0001_initial.py
  daycare/migrations/0003_rename_image_url_image_url.py
  daycare/models.py
  daycare/static/tests/images/daycare_image_test_01.jpeg
  daycare/static/tests/images/daycare_image_test_02.jpg
  daycare/test_daycare.py
  daycare/test_image.py
  daycare/validators.py
  resources/documents/HotailsDatabaseERD.png
Labels: Ready for merge

#65 Add static dog-owner users to dogowner app.
  dogowner/migrations/0002_test_data.py
  dogowner/migrations/0003_alter_dogowner_dog_picture_url.py
  dogowner/migrations/0004_test_static_data.py
  dogowner/models.py
  dogowner/test_dog_owner.py
  dogowner/validators.py
Labels: Ready for review

#73 🛠️ Refactor daycare tests
  daycare/test_daycare.py
Labels: Status/New, Ready for review

#71 Adding an "about" page to Hotails
  Hotails/urls.py
  main/templates/main/about.html
  main/templates/main/base_template.html
  main/templates/main/homepage.html
  main/tests.py
  main/urls.py
  main/views.py
  static/CSS/about.css
  static/Home.css
  static/Home.html
  static/images/Dog-Head-Wall.jpg
  static/nicepage.css
Labels: Ready for merge

#79 Change the creation of test data to use create method
  review/migrations/0002_test_data.py
Labels: Ready for review

#69 👤 Add Static daycares users for daycare app
  daycare/migrations/0004_static_daycare_users.py
  daycare/migrations/0005_image_data_migration.py
Labels: Ready for review

#62 Add login page
  Hotails/settings.py
  Hotails/urls.py
  Pipfile
  Pipfile.lock
  main/templates/main/base_template.html
  main/templates/main/login.html
  main/tests.py
  main/urls.py
  main/views.py
  static/css/Home.css
  static/css/login.css
  static/css/nicepage.css
  static/images/login_page.jpg
  tests/test_root_entrypoint.py
Labels: Ready for merge

#75 Search for review by daycare
  review/conftest.py
  review/models.py
  review/tests.py
Labels: Ready for review

#82 Updating ERD
  resources/documents/Hotails Database ERD.vsdx
  resources/documents/HotailsDatabaseERD.png
Labels: Ready for review

#84 Create static reviews for all DayCares
  review/migrations/0003_static_reviews_data.py
Labels: Ready for review, simple

#92 Creating static messages
  message/migrations/0003_static_messages.py
Labels: Ready for review
